"""Tests for PROJECT-STATUS.md generation and distribution.

Covers:
- ROADMAP.md parsing (with phases, missing, malformed)
- Status generation (single agent, multiple agents, git log, header)
- Distribution (writes to all clones via write_atomic)
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch

from vcompany.git.ops import GitResult
from vcompany.monitor.status_generator import (
    distribute_project_status,
    generate_project_status,
    get_agent_activity,
    parse_roadmap,
)
from vcompany.models.config import AgentConfig, ProjectConfig


def _make_config(*agents: tuple[str, str]) -> ProjectConfig:
    """Create a minimal ProjectConfig for testing."""
    agent_list = []
    for i, (aid, role) in enumerate(agents):
        agent_list.append(
            AgentConfig(
                id=aid,
                role=role,
                owns=[f"src/{aid}/"],
                consumes="context/",
                gsd_mode="full",
                system_prompt=f"You are {role}",
            )
        )
    return ProjectConfig(
        project="test-project",
        repo="https://github.com/test/repo",
        agents=agent_list,
    )


def _write_roadmap(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


ROADMAP_WITH_PHASES = """\
# Roadmap

- [x] **Phase 1: Foundation setup**
- [x] **Phase 2: Core API**
- [ ] **Phase 3: Integration layer**
- [ ] **Phase 4: Polish and deploy**
"""

ROADMAP_MALFORMED = """\
# Roadmap

- [x] **Phase 1: Foundation setup**
This line is not a phase
- [ ] Phase 3 missing asterisks
- [ ] **Phase 4: Valid again**
"""


class TestParseRoadmap:
    def test_parse_roadmap_with_phases(self, tmp_path: Path) -> None:
        roadmap = tmp_path / "ROADMAP.md"
        _write_roadmap(roadmap, ROADMAP_WITH_PHASES)

        result = parse_roadmap(roadmap)

        assert len(result) == 4
        assert result[0] == {"number": 1, "description": "Foundation setup", "status": "complete"}
        assert result[1] == {"number": 2, "description": "Core API", "status": "complete"}
        assert result[2] == {"number": 3, "description": "Integration layer", "status": "executing"}
        assert result[3] == {"number": 4, "description": "Polish and deploy", "status": "pending"}

    def test_parse_roadmap_missing(self, tmp_path: Path) -> None:
        roadmap = tmp_path / "nonexistent" / "ROADMAP.md"

        result = parse_roadmap(roadmap)

        assert len(result) == 1
        assert result[0]["status"] == "unknown"
        assert "unknown" in result[0]["description"].lower() or "Status unknown" in result[0]["description"]

    def test_parse_roadmap_malformed(self, tmp_path: Path) -> None:
        roadmap = tmp_path / "ROADMAP.md"
        _write_roadmap(roadmap, ROADMAP_MALFORMED)

        result = parse_roadmap(roadmap)

        # Should not raise, should return partial result
        assert len(result) >= 1
        # At least the valid lines should parse
        descriptions = [p["description"] for p in result]
        assert "Foundation setup" in descriptions


class TestGetAgentActivity:
    @patch("vcompany.monitor.status_generator.git_ops.log")
    def test_returns_stdout(self, mock_log: object) -> None:
        mock_log.return_value = GitResult(
            success=True, stdout="abc1234 feat: add auth\ndef5678 fix: login", stderr="", returncode=0
        )
        result = get_agent_activity(Path("/fake/clone"))
        assert "abc1234" in result
        assert "feat: add auth" in result

    @patch("vcompany.monitor.status_generator.git_ops.log")
    def test_returns_fallback_on_failure(self, mock_log: object) -> None:
        mock_log.return_value = GitResult(success=False, stdout="", stderr="fatal", returncode=1)
        result = get_agent_activity(Path("/fake/clone"))
        assert "No recent activity" in result


class TestGenerateProjectStatus:
    def test_generate_status_header(self, tmp_path: Path) -> None:
        config = _make_config(("backend", "Backend Developer"))
        project_dir = tmp_path / "project"
        clone_dir = project_dir / "clones" / "backend"
        _write_roadmap(clone_dir / ".planning" / "ROADMAP.md", ROADMAP_WITH_PHASES)

        now = datetime(2026, 3, 25, 8, 30, 0, tzinfo=timezone.utc)
        with patch("vcompany.monitor.status_generator.git_ops.log") as mock_log:
            mock_log.return_value = GitResult(success=True, stdout="abc feat", stderr="", returncode=0)
            result = generate_project_status(project_dir, config, now=now)

        assert result.startswith("# Project Status")
        assert "auto-generated by vco" in result
        assert "2026-03-25 08:30" in result

    def test_generate_status_single_agent(self, tmp_path: Path) -> None:
        config = _make_config(("backend", "Backend Developer"))
        project_dir = tmp_path / "project"
        clone_dir = project_dir / "clones" / "backend"
        _write_roadmap(clone_dir / ".planning" / "ROADMAP.md", ROADMAP_WITH_PHASES)

        now = datetime(2026, 3, 25, 8, 30, 0, tzinfo=timezone.utc)
        with patch("vcompany.monitor.status_generator.git_ops.log") as mock_log:
            mock_log.return_value = GitResult(success=True, stdout="abc feat", stderr="", returncode=0)
            result = generate_project_status(project_dir, config, now=now)

        # Agent section header with phase progress
        assert "BACKEND" in result
        assert "Phase 3/4" in result
        # Emoji markers
        assert "\u2705" in result  # checkmark for complete
        assert "\U0001f504" in result  # cycle arrows for executing
        assert "\u231b" in result  # hourglass for pending
        # Section structure
        assert "## Key Dependencies" in result
        assert "## Notes" in result

    def test_generate_status_multiple_agents(self, tmp_path: Path) -> None:
        config = _make_config(("backend", "Backend Dev"), ("frontend", "Frontend Dev"))
        project_dir = tmp_path / "project"

        for agent_id in ("backend", "frontend"):
            clone_dir = project_dir / "clones" / agent_id
            _write_roadmap(clone_dir / ".planning" / "ROADMAP.md", ROADMAP_WITH_PHASES)

        now = datetime(2026, 3, 25, 8, 30, 0, tzinfo=timezone.utc)
        with patch("vcompany.monitor.status_generator.git_ops.log") as mock_log:
            mock_log.return_value = GitResult(success=True, stdout="abc feat", stderr="", returncode=0)
            result = generate_project_status(project_dir, config, now=now)

        assert "## BACKEND" in result
        assert "## FRONTEND" in result

    def test_generate_status_includes_git_log(self, tmp_path: Path) -> None:
        config = _make_config(("backend", "Backend Dev"))
        project_dir = tmp_path / "project"
        clone_dir = project_dir / "clones" / "backend"
        _write_roadmap(clone_dir / ".planning" / "ROADMAP.md", ROADMAP_WITH_PHASES)

        now = datetime(2026, 3, 25, 8, 30, 0, tzinfo=timezone.utc)
        with patch("vcompany.monitor.status_generator.git_ops.log") as mock_log:
            mock_log.return_value = GitResult(
                success=True, stdout="abc1234 implement auth system", stderr="", returncode=0
            )
            result = generate_project_status(project_dir, config, now=now)

        assert "abc1234 implement auth system" in result


class TestDistributeProjectStatus:
    def test_distribute_writes_to_all_clones(self, tmp_path: Path) -> None:
        config = _make_config(("backend", "Backend Dev"), ("frontend", "Frontend Dev"))
        project_dir = tmp_path / "project"

        # Create clone dirs
        for agent_id in ("backend", "frontend"):
            (project_dir / "clones" / agent_id).mkdir(parents=True)

        content = "# Project Status\ntest content"
        count = distribute_project_status(project_dir, config, content)

        assert count == 2
        # Check context copy
        assert (project_dir / "context" / "PROJECT-STATUS.md").read_text() == content
        # Check clone copies
        assert (project_dir / "clones" / "backend" / "PROJECT-STATUS.md").read_text() == content
        assert (project_dir / "clones" / "frontend" / "PROJECT-STATUS.md").read_text() == content

    def test_distribute_uses_write_atomic(self, tmp_path: Path) -> None:
        config = _make_config(("backend", "Backend Dev"))
        project_dir = tmp_path / "project"
        (project_dir / "clones" / "backend").mkdir(parents=True)

        content = "# Project Status\ntest"
        with patch("vcompany.monitor.status_generator.write_atomic") as mock_wa:
            distribute_project_status(project_dir, config, content)

        # Should call write_atomic for context + 1 clone = 2 calls
        assert mock_wa.call_count == 2
