"""INTERACTIONS.md content generator.

Generates the reference document cataloging all known concurrent interaction
patterns in vCompany, with safety analysis and mitigations.
"""


def generate_interactions_md() -> str:
    """Return the full INTERACTIONS.md content as a string.

    Documents all known concurrent interaction scenarios with scenario
    description, safety assessment, and mitigation strategy.
    """
    return """# Known Interaction Patterns

This document catalogs known concurrent interaction scenarios in vCompany.
Auto-generated by vco. Review and update as new patterns are discovered.

## Monitor reads while agent writes

**Scenario:** The monitor loop reads an agent's STATE.md, ROADMAP.md, or git log
while the agent is actively writing to those files.

**Safe?** Yes

**Mitigation:** All coordination file writes use `write_atomic()` which creates a
temporary file then atomically renames it. Readers always see either the old complete
content or the new complete content -- never partial writes.

## Simultaneous git operations across clones

**Scenario:** Multiple agents run git operations (commit, push, pull) at the same
time in their respective clone directories.

**Safe?** Yes

**Mitigation:** Each agent operates in an independent repository clone with its own
`.git` directory. Git operations in separate repositories have no shared state and
cannot interfere with each other.

## PROJECT-STATUS.md distribution during agent read

**Scenario:** The monitor writes PROJECT-STATUS.md to an agent's clone directory
at the same moment the agent reads it.

**Safe?** Yes

**Mitigation:** Distribution uses `write_atomic()` which performs an atomic rename.
The agent either reads the old file or the new file -- the rename is instantaneous
from the filesystem perspective.

## Plan gate approve while agent is idle

**Scenario:** The monitor detects PM approval and sends the execute-phase command
to the agent's tmux pane while the agent is sitting idle at the Claude Code prompt.

**Safe?** Yes

**Mitigation:** The agent is at the prompt waiting for input. `send_keys` delivers
the command as keyboard input. There is no race because the agent is not processing
anything -- it is blocked waiting for user input.

## sync-context during agent execution

**Scenario:** `vco sync-context` writes INTERFACES.md or MILESTONE-SCOPE.md to an
agent's clone while the agent is mid-execution (reading or writing other files).

**Safe?** Yes

**Mitigation:** `write_atomic()` ensures the context file is either fully old or
fully new. The agent reads a consistent version. If the agent reads the old version
before the sync completes, it will pick up the new version on its next read.

## Multiple monitors (accidental)

**Scenario:** Two monitor processes are launched for the same project, either by
accident (two terminal tabs) or due to a restart race condition.

**Safe?** No -- UNSAFE

**Mitigation:** Duplicate monitors would produce duplicate Discord alerts, duplicate
plan gate approvals (potentially sending the same command twice), and conflicting
PROJECT-STATUS.md writes. Prevention: PID file at `{project}/state/monitor.pid`
checked on startup. If the PID file exists and the process is alive, the second
monitor must refuse to start. If the PID file is stale (process not alive), the
new monitor overwrites it and proceeds.

## Hook timeout during context compression

**Scenario:** An agent is busy with context compression (GSD session management)
when a hook fires (e.g., AskUserQuestion). The hook cannot get a response because
the agent is not at a decision point.

**Safe?** Conditionally safe

**Mitigation:** Hooks have independent timeout fallback behavior (Phase 5). The
AskUserQuestion hook waits for a configurable timeout (10 minutes), then returns
a deny response with a timeout reason. The agent receives the deny and continues
without hanging. Context compression completes independently.

## Simultaneous git pushes from multiple agents

**Scenario:** Two or more agents push to the remote repository at the same time.

**Safe?** Yes

**Mitigation:** Branch-per-agent isolation ensures each agent pushes to its own
branch (agent/{id}). Git push operations to different branches do not conflict.
The remote repository handles concurrent pushes to different refs without issues.
"""
